version: '3.1'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=Xhdhy  # Modified this line
      - POSTGRES_USER=dmarket
      - POSTGRES_DB=postgres

    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=kfira2002@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Xhdhy  # Modified this line
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
